<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<UseWPF>true</UseWPF>
		<Platforms>AnyCPU;x86</Platforms>
		<RootNamespace>MobiFlight</RootNamespace>
		<ProductName>MFConnector</ProductName>
		<AssemblyName>MFConnector</AssemblyName>
		<OutputType>WinExe</OutputType>
		<PlatformTarget>x86</PlatformTarget>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyTitle>MobiFlight Connector</AssemblyTitle>
		<Description>Open Source Flight Simulator Solution</Description>
		<Product>MobiFlight Connector</Product>
		<Copyright>Copyright Sebastian Moebius 2014 - 2026</Copyright>
		<ApplicationIcon>mobiflight.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug'">
		<DefineConstants>TRACE;MOBIFLIGHT;DEBUG;SIMCONNECT;ARCAZE</DefineConstants>
		<DocumentationFile>bin\Debug\MFConnector.xml</DocumentationFile>
		<WarningLevel>2</WarningLevel>
		<CodeAnalysisIgnoreBuiltInRuleSets>false</CodeAnalysisIgnoreBuiltInRuleSets>
		<CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release'">
		<DefineConstants>TRACE;CODE_ANALYSIS;MOBIFLIGHT;RELEASE;SIMCONNECT;ARCAZE</DefineConstants>
		<WarningLevel>2</WarningLevel>
		<UseVSHostingProcess>false</UseVSHostingProcess>
		<CodeAnalysisRuleSet>MinimumRecommendedRules.ruleset</CodeAnalysisRuleSet>
		<CodeAnalysisIgnoreBuiltInRuleSets>false</CodeAnalysisIgnoreBuiltInRuleSets>
		<CodeAnalysisIgnoreBuiltInRules>false</CodeAnalysisIgnoreBuiltInRules>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="mobiflight.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Device.Net" Version="4.2.1" />
		<PackageReference Include="FSUIPCClientDLL" Version="3.3.16" />
		<PackageReference Include="GraphQL.Client" Version="6.1.0" />
		<PackageReference Include="GraphQL.Client.Serializer.Newtonsoft" Version="6.1.0" />
		<PackageReference Include="GraphQL.Primitives" Version="6.1.0" />
		<PackageReference Include="Hid.Net" Version="4.2.1" />
		<PackageReference Include="HidSharp" Version="2.6.4" />
		<PackageReference Include="Microsoft.ApplicationInsights" Version="2.21.0" />
		<PackageReference Include="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" Version="2.21.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3856.49" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.DirectInput" Version="4.2.0" />
		<PackageReference Include="System.Management" Version="10.0.5" />
		<PackageReference Include="WebSocketSharp-netstandard" Version="1.0.1" />
		<PackageReference Include="XPlaneConnector" Version="1.3.0" />
		<PackageReference Include="System.IO.Ports" Version="10.0.5" />
		<PackageReference Include="System.Net.WebSockets.Client.Managed" Version="1.0.22" />
		<PackageReference Include="System.Reactive" Version="6.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\CommandMessenger.Transport.Serial\CommandMessenger.Transport.Serial.csproj" />
		<ProjectReference Include="..\CommandMessenger\CommandMessenger.csproj" />
		<ProjectReference Include="..\MobiFlightWwFcu\MobiFlightWwFcu.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="ArcazeHid, Version=1.0.0.0, Culture=neutral, processorArchitecture=x86">
			<HintPath>..\..\lib\ArcazeHid.dll</HintPath>
		</Reference>
		<Reference Include="Microsoft.FlightSimulator.SimConnect, Version=10.0.61259.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=x86">
			<HintPath>SimConnectFSX\Microsoft.FlightSimulator.SimConnect.dll</HintPath>
		</Reference>
		<Reference Include="Midi">
			<HintPath>..\..\lib\Midi.dll</HintPath>
		</Reference>
		<Reference Include="NCalc">
			<HintPath>..\..\lib\NCalc.dll</HintPath>
		</Reference>
		<Reference Include="vJoyInterfaceWrap">
			<HintPath>..\..\lib\vJoyInterfaceWrap.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<None Update="Boards\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Community\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Devices\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="examples\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="firmware\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Joysticks\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="MidiBoards\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Presets\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</None>
		<None Update="Scripts\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="frontend\dist\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="MSFS2020-module\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Arduino\**">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Content Include="..\..\Python\*.zip">
			<Link>Python\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\..\lib\vJoyInterface.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
		<Content Include="..\..\lib\x86\SimConnect.dll">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
			<_Parameter1>MobiFlightUnitTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Properties\Settings.Designer.cs">
			<DesignTimeSharedInput>True</DesignTimeSharedInput>
			<AutoGen>True</AutoGen>
			<DependentUpon>Settings.settings</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<None Update="Properties\Settings.settings">
			<Generator>SettingsSingleFileGenerator</Generator>
			<LastGenOutput>Settings.Designer.cs</LastGenOutput>
		</None>
	</ItemGroup>
</Project>