changelog:
  exclude:
    labels:
      - ignore-for-release-notes
      - dependencies
  categories:
    - title: New Feature 🎉
      labels:
        - feature
    - title: Firmware & profile updates 🚀
      labels:
        - firmware
        - profile
    - title: Improvement ✨
      labels:
        - enhancement
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Bug Fixes (BETA) 🐛
      labels:
        - bug_beta
    - title: Documentation 📚
      labels:
        - documentation
    - title: Development 💻
      labels:
        - development    
    - title: Other Changes ⚡
      labels:
        - "*"
