<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="FSUIPCClientDLL" Version="3.3.16" />
    <PackageVersion Include="GraphQL.Client" Version="6.1.0" />
    <PackageVersion Include="GraphQL.Client.Serializer.Newtonsoft" Version="6.1.0" />
    <PackageVersion Include="GraphQL.Primitives" Version="6.1.0" />
    <PackageVersion Include="HidSharp" Version="2.6.4" />
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="2.23.0" />
    <PackageVersion Include="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" Version="2.23.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.5" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.Telemetry" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport.Abstractions" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.VSTestBridge" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Testing.Platform.MSBuild" Version="2.1.0" />
    <PackageVersion Include="Microsoft.Web.WebView2" Version="1.0.4129.50" />
    <PackageVersion Include="MSTest.TestAdapter" Version="4.3.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="4.3.3" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="Newtonsoft.Json.Schema" Version="4.0.1" />
    <PackageVersion Include="SharpDX" Version="4.2.0" />
    <PackageVersion Include="SharpDX.DirectInput" Version="4.2.0" />
    <PackageVersion Include="System.Collections.Immutable" Version="10.0.9" />
    <PackageVersion Include="System.Diagnostics.DiagnosticSource" Version="10.0.9" />
    <PackageVersion Include="System.IO.Ports" Version="10.0.9" />
    <PackageVersion Include="System.Management" Version="10.0.5" />
    <PackageVersion Include="System.Net.WebSockets.Client.Managed" Version="1.0.22" />
    <PackageVersion Include="System.Reactive" Version="6.1.0" />
    <PackageVersion Include="System.Reflection.Metadata" Version="10.0.9" />
    <PackageVersion Include="WebSocketSharp-netstandard" Version="1.0.1" />
    <PackageVersion Include="XPlaneConnector" Version="1.3.0" />
  </ItemGroup>
</Project>
