//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcazeUSB {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcazeUSB.ProjectMessages", typeof(ProjectMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  ähnelt.
        /// </summary>
        internal static string conf {
            get {
                return ResourceManager.GetString("conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The address of a Display Module must not be null. Please review your config. ähnelt.
        /// </summary>
        internal static string ConfigErrorException_AddressNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_AddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The serial of an Arcaze Module must not be null. Please review your config. ähnelt.
        /// </summary>
        internal static string ConfigErrorException_SerialNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_SerialNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on writing values to Display Module. Please review your config. ähnelt.
        /// </summary>
        internal static string ConfigErrorException_WritingDisplay {
            get {
                return ResourceManager.GetString("ConfigErrorException_WritingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die unsaved ähnelt.
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Disconnect ähnelt.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Find ähnelt.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FSUIPC Status ähnelt.
        /// </summary>
        internal static string fsuipcStatus {
            get {
                return ResourceManager.GetString("fsuipcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hint ähnelt.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input validation ähnelt.
        /// </summary>
        internal static string InputValidation {
            get {
                return ResourceManager.GetString("InputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcaze Pin ähnelt.
        /// </summary>
        internal static string LabelPrecondition_ArcazePin {
            get {
                return ResourceManager.GetString("LabelPrecondition_ArcazePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config item ähnelt.
        /// </summary>
        internal static string LabelPrecondition_ConfigItem {
            get {
                return ResourceManager.GetString("LabelPrecondition_ConfigItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        internal static string LabelPrecondition_None {
            get {
                return ResourceManager.GetString("LabelPrecondition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are still changes not uploaded to your modules. You will loose these changes if you close the form. Do you really want to continue? ähnelt.
        /// </summary>
        internal static string MFModuleConfigChanged {
            get {
                return ResourceManager.GetString("MFModuleConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die none ähnelt.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Offset ähnelt.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please Choose ähnelt.
        /// </summary>
        internal static string Please_Choose {
            get {
                return ResourceManager.GetString("Please_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a pin. ähnelt.
        /// </summary>
        internal static string Please_select_a_pin {
            get {
                return ResourceManager.GetString("Please_select_a_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a port. ähnelt.
        /// </summary>
        internal static string Please_select_a_port {
            get {
                return ResourceManager.GetString("Please_select_a_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retry ähnelt.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Running ähnelt.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FSUIPC is connected. ähnelt.
        /// </summary>
        internal static string statusFsuipcConnected {
            get {
                return ResourceManager.GetString("statusFsuipcConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stopped ähnelt.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copy ähnelt.
        /// </summary>
        internal static string suffixCopy {
            get {
                return ResourceManager.GetString("suffixCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Test Mode ähnelt.
        /// </summary>
        internal static string TestMode {
            get {
                return ResourceManager.GetString("TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Execute Config line by line and trigger the corresponding pin ähnelt.
        /// </summary>
        internal static string TestModeToolTip {
            get {
                return ResourceManager.GetString("TestModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Config object was null. ähnelt.
        /// </summary>
        internal static string uiException_ConfigItemNotFound {
            get {
                return ResourceManager.GetString("uiException_ConfigItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double-click row to add new config... ähnelt.
        /// </summary>
        internal static string uiLabelDoubleClickToAddConfig {
            get {
                return ResourceManager.GetString("uiLabelDoubleClickToAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Application is now running in the background. ähnelt.
        /// </summary>
        internal static string uiMessageApplicationIsRunningInBackgroundMode {
            get {
                return ResourceManager.GetString("uiMessageApplicationIsRunningInBackgroundMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Arcaze module has been removed. ähnelt.
        /// </summary>
        internal static string uiMessageAraceUSBHasBeenRemoved {
            get {
                return ResourceManager.GetString("uiMessageAraceUSBHasBeenRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection to the arcaze module got lost ähnelt.
        /// </summary>
        internal static string uiMessageArcazeConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageArcazeConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Arcaze module found. ähnelt.
        /// </summary>
        internal static string uiMessageArcazeModuleFound {
            get {
                return ResourceManager.GetString("uiMessageArcazeModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The config file passed as parameter does not exist. ähnelt.
        /// </summary>
        internal static string uiMessageCmdParamConfigFileDoesNotExist {
            get {
                return ResourceManager.GetString("uiMessageCmdParamConfigFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This config line is not saved yet.
        ///Set the description text and use the edit button then. ähnelt.
        /// </summary>
        internal static string uiMessageConfigLineNotSavedYet {
            get {
                return ResourceManager.GetString("uiMessageConfigLineNotSavedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error on loading presets. Presets are not available for selection. ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_ErrorLoadingPresets {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ErrorLoadingPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Presets file not found in current directory. ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_PresetsNotFound {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_PresetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide the address of the desired Led Display Module. It must be numeric, e.g. 1 ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_ProvideLedDisplayAddress {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ProvideLedDisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please select a module by choosing a valid serial from the list. ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_SelectArcaze {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectArcaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please provide a value for comparison. ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_SelectComparison {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown precondition type from config ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_UnknownPreconditionType {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_UnknownPreconditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please review the value and provide a valid hex format (0-F). ähnelt.
        /// </summary>
        internal static string uiMessageConfigWizard_ValidHexFormat {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ValidHexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are unsaved changes in your configuration.
        ///Do you want to save them now? ähnelt.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsaved {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check ähnelt.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsavedTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to create a new config?
        ///All unsaved changes will get lost. ähnelt.
        /// </summary>
        internal static string uiMessageConfirmNewConfig {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please confirm ähnelt.
        /// </summary>
        internal static string uiMessageConfirmNewConfigTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occured on parsing your value formula. Please review and correct any errors. ähnelt.
        /// </summary>
        internal static string uiMessageErrorOnParsingExpression {
            get {
                return ResourceManager.GetString("uiMessageErrorOnParsingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Flight Simulator has been closed. Execution of config has been stopped. Restart your flight simulator to restart config. ähnelt.
        /// </summary>
        internal static string uiMessageFsHasBeenStopped {
            get {
                return ResourceManager.GetString("uiMessageFsHasBeenStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection to FSUIPC got lost ähnelt.
        /// </summary>
        internal static string uiMessageFsuipcConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid Value! Only use hex-encoded numbers. ähnelt.
        /// </summary>
        internal static string uiMessageInvalidValueHexOnly {
            get {
                return ResourceManager.GetString("uiMessageInvalidValueHexOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MFConnector still active ähnelt.
        /// </summary>
        internal static string uiMessageMFConnectorInterfaceActive {
            get {
                return ResourceManager.GetString("uiMessageMFConnectorInterfaceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The config file has to be converted to work correctly. Please save with new file extension. ähnelt.
        /// </summary>
        internal static string uiMessageMigrateConfigFileYesNo {
            get {
                return ResourceManager.GetString("uiMessageMigrateConfigFileYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die It seems that your arcaze modules are not configured. This is a new feature to better support &quot;Extension Modules&quot;.
        ///
        ///You should configure them now. ähnelt.
        /// </summary>
        internal static string uiMessageModulesNotConfiguredYet {
            get {
                return ResourceManager.GetString("uiMessageModulesNotConfiguredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No module found. ähnelt.
        /// </summary>
        internal static string uiMessageNoArcazeModuleFound {
            get {
                return ResourceManager.GetString("uiMessageNoArcazeModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There are no orphaned serials in the current config. ähnelt.
        /// </summary>
        internal static string uiMessageNoOrphanedSerialsFound {
            get {
                return ResourceManager.GetString("uiMessageNoOrphanedSerialsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not implemented yet. ähnelt.
        /// </summary>
        internal static string uiMessageNotImplementedYet {
            get {
                return ResourceManager.GetString("uiMessageNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Precondition is not satisfied ähnelt.
        /// </summary>
        internal static string uiMessagePreconditionNotSatisfied {
            get {
                return ResourceManager.GetString("uiMessagePreconditionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die http://mobiflight.moebiuz.de/dokumentation/software.html ähnelt.
        /// </summary>
        internal static string WebsiteUrlHelp {
            get {
                return ResourceManager.GetString("WebsiteUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die XPUIPC Status ähnelt.
        /// </summary>
        internal static string xpuipcStatus {
            get {
                return ResourceManager.GetString("xpuipcStatus", resourceCulture);
            }
        }
    }
}
