CmdMessenger: CommandMessenger.BinaryConverter Class Reference
CommandMessenger.BinaryConverter Class Reference
Static Public Member Functions
static string ToString (Single value)
Convert a float into a string representation.
static string ToString (Double value)
Convert a Double into a string representation.
static string ToString (int value)
Convert an int into a string representation.
static string ToString (uint value)
Convert an unsigned int into a string representation.
static string ToString (short value)
Convert a short into a string representation.
static string ToString (ushort value)
Convert an unsigned an unsigned short into a string representation.
static string ToString (byte value)
Convert a byte into a string representation.
static Single ToFloat (String value)
Converts a string to a float.
static Double ToDouble (String value)
Converts a string representation to a double.
static Int32 ToInt32 (String value)
Converts a string representation to an int 32.
static UInt32 ToUInt32 (String value)
Converts a string representation to a u int 32.
static UInt16 ToUInt16 (String value)
Converts a string representation to a u int 16.
static Int16 ToInt16 (String value)
Converts a string representation to an int 16.
static byte ToByte (String value)
Converts a string representation to a byte.
static byte[] EscapedStringToBytes (String value)
Converts an escaped string to a bytes array.
Properties
Encoding StringEncoder set
Sets the string encoder.
Member Function Documentation
static byte [] CommandMessenger.BinaryConverter.EscapedStringToBytes (String value) inline static
Converts an escaped string to a bytes array.
Parameters
value The value to be converted.
Returns
input value as an escaped string.
Referenced by CommandMessenger.BinaryConverter.ToByte(), CommandMessenger.BinaryConverter.ToDouble(), CommandMessenger.BinaryConverter.ToFloat(), CommandMessenger.BinaryConverter.ToInt16(), CommandMessenger.BinaryConverter.ToInt32(), CommandMessenger.BinaryConverter.ToUInt16(), and CommandMessenger.BinaryConverter.ToUInt32().
         {
             try
             {
                 string unEscapedValue = Escaping.Unescape(value);
                 return _stringEncoder.GetBytes(unEscapedValue);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static byte CommandMessenger.BinaryConverter.ToByte (String value) inline static
Converts a string representation to a byte.
Parameters
value The value to be converted.
Returns
Input string as a byte?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return bytes[0];
             }
             catch (Exception)
             {
                 return null;
             }
         }
static Double CommandMessenger.BinaryConverter.ToDouble (String value) inline static
Converts a string representation to a double.
Parameters
value The value to be converted.
Returns
Input string as a Double?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToDouble(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static Single CommandMessenger.BinaryConverter.ToFloat (String value) inline static
Converts a string to a float.
Parameters
value The value to be converted.
Returns
Input string as a Single?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToSingle(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static Int16 CommandMessenger.BinaryConverter.ToInt16 (String value) inline static
Converts a string representation to an int 16.
Parameters
value The value to be converted.
Returns
This object as an Int16?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToInt16(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static Int32 CommandMessenger.BinaryConverter.ToInt32 (String value) inline static
Converts a string representation to an int 32.
Parameters
value The value to be converted.
Returns
This object as an Int32?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToInt32(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (Single value) inline static
Convert a float into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (Double value) inline static
Convert a Double into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (int value) inline static
Convert an int into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (uint value) inline static
Convert an unsigned int into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (short value) inline static
Convert a short into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (ushort value) inline static
Convert an unsigned an unsigned short into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 byte[] byteArray = BitConverter.GetBytes(value);
                 return BytesToEscapedString(byteArray);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static string CommandMessenger.BinaryConverter.ToString (byte value) inline static
Convert a byte into a string representation.
Parameters
value The value to be converted.
Returns
A string representation of this object.
         {
             try
             {
                 return BytesToEscapedString(new byte[] {value});
             }
             catch (Exception)
             {
                 return null;
             }
         }
static UInt16 CommandMessenger.BinaryConverter.ToUInt16 (String value) inline static
Converts a string representation to a u int 16.
Parameters
value The value to be converted.
Returns
Input string as a UInt16?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToUInt16(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
static UInt32 CommandMessenger.BinaryConverter.ToUInt32 (String value) inline static
Converts a string representation to a u int 32.
Parameters
value The value to be converted.
Returns
Input string as a UInt32?
References CommandMessenger.BinaryConverter.EscapedStringToBytes().
         {
             try
             {
                 byte[] bytes = EscapedStringToBytes(value);
                 return BitConverter.ToUInt32(bytes, 0);
             }
             catch (Exception)
             {
                 return null;
             }
         }
Property Documentation
Encoding StringEncoder CommandMessenger.BinaryConverter.set
Sets the string encoder.
The string encoder.
The documentation for this class was generated from the following file:
D:/My Documents/Github/Arduino-Code-and-Libraries/Libraries/CmdMessenger/CSharp/CommandMessenger/BinaryConverter.cs