<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DefineConstants>TRACE;DEBUG;ARCAZE</DefineConstants>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DefineConstants>TRACE;ARCAZE</DefineConstants>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
		<PlatformTarget>x86</PlatformTarget>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
		<PackageReference Include="Microsoft.Testing.Extensions.Telemetry" Version="2.1.0" />
		<PackageReference Include="Microsoft.Testing.Platform" Version="2.1.0" />
		<PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.1.0" />
		<PackageReference Include="Moq" Version="4.20.72" />
		<PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
		<PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="assets\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\MobiFlightConnector\MobiFlightConnector.csproj" />
	</ItemGroup>

	<Target Name="CustomPreBuild" BeforeTargets="Build">
		<ItemGroup>
			<MccFiles Include="$(SolutionDir)src\MobiFlightConnector\examples\*.mcc" />
		</ItemGroup>

		<MakeDir Directories="$(TargetDir)assets\Base\ConfigFile" />

		<Copy SourceFiles="@(MccFiles)" DestinationFolder="$(TargetDir)assets\Base\ConfigFile" SkipUnchangedFiles="true" />

		<Copy SourceFiles="$(SolutionDir)lib\x86\SimConnect.dll" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
	</Target>

</Project>
