<Project Sdk="MSTest.Sdk/4.0.2">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<PlatformTarget>x86</PlatformTarget>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseVSTest>true</UseVSTest>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DefineConstants>TRACE;DEBUG;ARCAZE</DefineConstants>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DefineConstants>TRACE;ARCAZE</DefineConstants>
		<NoWarn>$(NoWarn);WFO1000</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Testing.Extensions.Telemetry" Version="2.1.0" />
		<PackageReference Include="Microsoft.Testing.Platform" Version="2.3.3" />
		<PackageReference Include="Microsoft.Testing.Platform.MSBuild" Version="2.3.3" />
		<PackageReference Include="Moq" Version="4.20.72" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="assets\**">
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\MobiFlightConnector\MobiFlightConnector.csproj" />
		<ProjectReference Include="..\..\src\MobiFlightWwFcu\MobiFlightWwFcu.csproj" />
	</ItemGroup>

	<Target Name="CustomPreBuild" BeforeTargets="Build">
		<ItemGroup>
			<MccFiles Include="$(SolutionDir)src\MobiFlightConnector\examples\*.mcc" />
		</ItemGroup>

		<MakeDir Directories="$(TargetDir)assets\Base\ConfigFile" />

		<Copy SourceFiles="@(MccFiles)" DestinationFolder="$(TargetDir)assets\Base\ConfigFile"
			SkipUnchangedFiles="true" />

		<Copy SourceFiles="$(SolutionDir)lib\x86\SimConnect.dll" DestinationFolder="$(TargetDir)"
			SkipUnchangedFiles="true" />
	</Target>

</Project>