<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyTitle>MobiFlight-Installer</AssemblyTitle>
		<ApplicationIcon>mobiflight.ico</ApplicationIcon>
		<Company>MobiFlight</Company>
		<Product>MobiFlight-Installer</Product>
		<Copyright>Copyright 2026</Copyright>
		<Title>MobiFlight-Installer</Title>
		<ProductName>MobiFlight-Installer</ProductName>
		<AssemblyName>MobiFlight-Installer</AssemblyName>
		<OutputType>WinExe</OutputType>
		<PlatformTarget>x86</PlatformTarget>
		<RuntimeIdentifier>win-x86</RuntimeIdentifier>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="mobiflight.ico" />
	</ItemGroup>

</Project>