<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyTitle>MobiFlight-Installer</AssemblyTitle>
		<ApplicationIcon>mobiflight.ico</ApplicationIcon>
		<Company>MobiFlight</Company>
		<Product>MobiFlight-Installer</Product>
		<Copyright>Copyright 2026</Copyright>
		<Title>MobiFlight-Installer</Title>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="mobiflight.ico" />
	</ItemGroup>

</Project>
