CmdMessenger: CommandMessenger.ReceivedCommand Class Reference
CommandMessenger.ReceivedCommand Class Reference
A command received from CmdMessenger
Public Member Functions
ReceivedCommand ()
Default constructor.
ReceivedCommand (string[] arguments)
Constructor.
bool Next ()
Fetches the next argument.
bool Available ()
returns if a next command is available
Int16 ReadInt16Arg ()
Reads the current argument as short value.
UInt16 ReadUInt16Arg ()
Reads the current argument as unsigned short value.
bool ReadBoolArg ()
Reads the current argument as boolean value.
Int32 ReadInt32Arg ()
Reads the current argument as int value.
UInt32 ReadUInt32Arg ()
Reads the current argument as unsigned int value.
Single ReadFloatArg ()
Reads the current argument as a float value.
Single ReadDoubleArg ()
Reads the current argument as a double value.
String ReadStringArg ()
Reads the current argument as a string value.
Single ReadBinFloatArg ()
Reads the current binary argument as a float value.
Double ReadBinDoubleArg ()
Reads the current binary argument as a double value.
Int16 ReadBinInt16Arg ()
Reads the current binary argument as a short value.
UInt16 ReadBinUInt16Arg ()
Reads the current binary argument as a unsigned short value.
Int32 ReadBinInt32Arg ()
Reads the current binary argument as a int value.
UInt32 ReadBinUInt32Arg ()
Reads the current binary argument as a unsigned int value.
String ReadBinStringArg ()
Reads the current binary argument as a string value.
bool ReadBinBoolArg ()
Reads the current binary argument as a boolean value.
Properties
long TimeStamp [get, set]
Gets or sets the time stamp.
bool Ok [get]
Returns whether this is a valid & filled command.
string this[int index] [get]
Indexer to get arguments directly.
int CommandId [get]
Gets the command ID.
Detailed Description
A command received from CmdMessenger
Constructor & Destructor Documentation
CommandMessenger.ReceivedCommand.ReceivedCommand () inline
Default constructor.
         {
         }
CommandMessenger.ReceivedCommand.ReceivedCommand (string[] arguments) inline
Constructor.
Parameters
arguments All command arguments, first one is command ID
         {
             _arguments = arguments;
         }
Member Function Documentation
bool CommandMessenger.ReceivedCommand.Available () inline
returns if a next command is available
Returns
true if it succeeds, false if it fails.
References CommandMessenger.ReceivedCommand.Next().
         {
             return Next();
         }
bool CommandMessenger.ReceivedCommand.Next () inline
Fetches the next argument.
Returns
true if it succeeds, false if it fails.
Referenced by CommandMessenger.ReceivedCommand.Available(), CommandMessenger.ReceivedCommand.ReadBinBoolArg(), CommandMessenger.ReceivedCommand.ReadBinDoubleArg(), CommandMessenger.ReceivedCommand.ReadBinFloatArg(), CommandMessenger.ReceivedCommand.ReadBinInt16Arg(), CommandMessenger.ReceivedCommand.ReadBinInt32Arg(), CommandMessenger.ReceivedCommand.ReadBinStringArg(), CommandMessenger.ReceivedCommand.ReadBinUInt16Arg(), CommandMessenger.ReceivedCommand.ReadBinUInt32Arg(), CommandMessenger.ReceivedCommand.ReadDoubleArg(), CommandMessenger.ReceivedCommand.ReadFloatArg(), CommandMessenger.ReceivedCommand.ReadInt16Arg(), CommandMessenger.ReceivedCommand.ReadInt32Arg(), CommandMessenger.ReceivedCommand.ReadStringArg(), CommandMessenger.ReceivedCommand.ReadUInt16Arg(), and CommandMessenger.ReceivedCommand.ReadUInt32Arg().
         {
             // If this parameter has already been read, see if there is another one
             if (_dumped)
             {
                 if (_parameter < _arguments.Length - 1)
                 {
                     _parameter++;
                     _dumped = false;
                     return true;
                 }
                 else
                 {
                     return false;
                 }
             }
             return true;
         }
bool CommandMessenger.ReceivedCommand.ReadBinBoolArg () inline
Reads the current binary argument as a boolean value.
Returns
The boolean value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToByte(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (current != 0);
                 }
             }
             return false;
         }
Double CommandMessenger.ReceivedCommand.ReadBinDoubleArg () inline
Reads the current binary argument as a double value.
Returns
The double value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToDouble(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (double) current;
                 }
             }
             return 0;
         }
Single CommandMessenger.ReceivedCommand.ReadBinFloatArg () inline
Reads the current binary argument as a float value.
Returns
The float value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToFloat(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (float) current;
                 }
             }
             return 0;
         }
Int16 CommandMessenger.ReceivedCommand.ReadBinInt16Arg () inline
Reads the current binary argument as a short value.
Returns
The short value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToInt16(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (Int16) current;
                 }
             }
             return 0;
         }
Int32 CommandMessenger.ReceivedCommand.ReadBinInt32Arg () inline
Reads the current binary argument as a int value.
Returns
The int value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToInt32(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (Int32) current;
                 }
             }
             return 0;
         }
String CommandMessenger.ReceivedCommand.ReadBinStringArg () inline
Reads the current binary argument as a string value.
Returns
The string value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 if (_arguments[_parameter] != null)
                 {
                     _dumped = true;
                     return Escaping.Unescape(_arguments[_parameter]);
                 }
             }
             return "";
         }
UInt16 CommandMessenger.ReceivedCommand.ReadBinUInt16Arg () inline
Reads the current binary argument as a unsigned short value.
Returns
The unsigned short value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToUInt16(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (UInt16) current;
                 }
             }
             return 0;
         }
UInt32 CommandMessenger.ReceivedCommand.ReadBinUInt32Arg () inline
Reads the current binary argument as a unsigned int value.
Returns
The unsigned int value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 var current = BinaryConverter.ToUInt32(_arguments[_parameter]);
                 if (current != null)
                 {
                     _dumped = true;
                     return (UInt32) current;
                 }
             }
             return 0;
         }
bool CommandMessenger.ReceivedCommand.ReadBoolArg () inline
Reads the current argument as boolean value.
Returns
The boolean value.
References CommandMessenger.ReceivedCommand.ReadInt32Arg().
         {
             return (ReadInt32Arg() != 0);
         }
Single CommandMessenger.ReceivedCommand.ReadDoubleArg () inline
Reads the current argument as a double value.
Returns
The unsigned double value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 Single current;
                 if (Single.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
Single CommandMessenger.ReceivedCommand.ReadFloatArg () inline
Reads the current argument as a float value.
Returns
The float value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 Single current;
                 if (Single.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
Int16 CommandMessenger.ReceivedCommand.ReadInt16Arg () inline
Reads the current argument as short value.
Returns
The short value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 Int16 current;
                 if (Int16.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
Int32 CommandMessenger.ReceivedCommand.ReadInt32Arg () inline
Reads the current argument as int value.
Returns
The int value.
References CommandMessenger.ReceivedCommand.Next().
Referenced by CommandMessenger.ReceivedCommand.ReadBoolArg().
         {
             if (Next())
             {
                 Int32 current;
                 if (Int32.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
String CommandMessenger.ReceivedCommand.ReadStringArg () inline
Reads the current argument as a string value.
Returns
The string value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 if (_arguments[_parameter] != null)
                 {
                     _dumped = true;
                     return _arguments[_parameter];
                 }
             }
             return "";
         }
UInt16 CommandMessenger.ReceivedCommand.ReadUInt16Arg () inline
Reads the current argument as unsigned short value.
Returns
The unsigned short value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 UInt16 current;
                 if (UInt16.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
UInt32 CommandMessenger.ReceivedCommand.ReadUInt32Arg () inline
Reads the current argument as unsigned int value.
Returns
The unsigned int value.
References CommandMessenger.ReceivedCommand.Next().
         {
             if (Next())
             {
                 UInt32 current;
                 if (UInt32.TryParse(_arguments[_parameter], out current))
                 {
                     _dumped = true;
                     return current;
                 }
             }
             return 0;
         }
Property Documentation
int CommandMessenger.ReceivedCommand.CommandId get
Gets the command ID.
The command ID.
Referenced by CommandMessenger.CmdMessenger.HandleMessage().
bool CommandMessenger.ReceivedCommand.Ok get
Returns whether this is a valid & filled command.
true if ok, false if not.
Referenced by CommandMessenger.CmdMessenger.HandleMessage().
string CommandMessenger.ReceivedCommand.this[int index] get
Indexer to get arguments directly.
The indexed item.
long CommandMessenger.ReceivedCommand.TimeStamp get set
Gets or sets the time stamp.
The time stamp.
The documentation for this class was generated from the following file:
D:/My Documents/Github/Arduino-Code-and-Libraries/Libraries/CmdMessenger/CSharp/CommandMessenger/ReceivedCommand.cs