//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobiFlight.ProjectMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MobiFlight.ProjectMessages.ProjectMessages", typeof(ProjectMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address of a Display Module must not be null. Please review your config..
        /// </summary>
        internal static string ConfigErrorException_AddressNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_AddressNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serial of an Arcaze Module must not be null. Please review your config..
        /// </summary>
        internal static string ConfigErrorException_SerialNull {
            get {
                return ResourceManager.GetString("ConfigErrorException_SerialNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on writing values to Display Module. Please review your config..
        /// </summary>
        internal static string ConfigErrorException_WritingDisplay {
            get {
                return ResourceManager.GetString("ConfigErrorException_WritingDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unsaved.
        /// </summary>
        internal static string DefaultFileName {
            get {
                return ResourceManager.GetString("DefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string Find {
            get {
                return ResourceManager.GetString("Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSUIPC Status.
        /// </summary>
        internal static string fsuipcStatus {
            get {
                return ResourceManager.GetString("fsuipcStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input validation.
        /// </summary>
        internal static string InputValidation {
            get {
                return ResourceManager.GetString("InputValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arcaze Pin.
        /// </summary>
        internal static string Label_Precondition_ArcazePin {
            get {
                return ResourceManager.GetString("Label_Precondition_ArcazePin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose config.
        /// </summary>
        internal static string Label_Precondition_choose_config {
            get {
                return ResourceManager.GetString("Label_Precondition_choose_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose variable.
        /// </summary>
        internal static string Label_Precondition_choose_variable {
            get {
                return ResourceManager.GetString("Label_Precondition_choose_variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config item.
        /// </summary>
        internal static string Label_Precondition_ConfigItem {
            get {
                return ResourceManager.GetString("Label_Precondition_ConfigItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string Label_Precondition_None {
            get {
                return ResourceManager.GetString("Label_Precondition_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight Variable.
        /// </summary>
        internal static string Label_Precondition_Variable {
            get {
                return ResourceManager.GetString("Label_Precondition_Variable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are still changes not uploaded to your modules. You will lose these changes if you close the form. Do you really want to continue?.
        /// </summary>
        internal static string MFModuleConfigChanged {
            get {
                return ResourceManager.GetString("MFModuleConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset.
        /// </summary>
        internal static string Offset {
            get {
                return ResourceManager.GetString("Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Choose.
        /// </summary>
        internal static string Please_Choose {
            get {
                return ResourceManager.GetString("Please_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a pin..
        /// </summary>
        internal static string Please_select_a_pin {
            get {
                return ResourceManager.GetString("Please_select_a_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a port..
        /// </summary>
        internal static string Please_select_a_port {
            get {
                return ResourceManager.GetString("Please_select_a_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FSUIPC is connected..
        /// </summary>
        internal static string statusFsuipcConnected {
            get {
                return ResourceManager.GetString("statusFsuipcConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string suffixCopy {
            get {
                return ResourceManager.GetString("suffixCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Mode.
        /// </summary>
        internal static string TestMode {
            get {
                return ResourceManager.GetString("TestMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Config line by line and trigger the corresponding pin.
        /// </summary>
        internal static string TestModeToolTip {
            get {
                return ResourceManager.GetString("TestModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config object was null..
        /// </summary>
        internal static string uiException_ConfigItemNotFound {
            get {
                return ResourceManager.GetString("uiException_ConfigItemNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires the use of pin {1} which is already assigned to another module. Remove the pin assignment from the other module then try adding {0} again..
        /// </summary>
        internal static string uiI2CPinInUse {
            get {
                return ResourceManager.GetString("uiI2CPinInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I2C pin in use.
        /// </summary>
        internal static string uiI2CPinInUseHint {
            get {
                return ResourceManager.GetString("uiI2CPinInUseHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double-click row to add new config....
        /// </summary>
        internal static string uiLabelDoubleClickToAddConfig {
            get {
                return ResourceManager.GetString("uiLabelDoubleClickToAddConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible module.
        /// </summary>
        internal static string uiLabelModuleNAME_UNKNOWN {
            get {
                return ResourceManager.GetString("uiLabelModuleNAME_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible.
        /// </summary>
        internal static string uiLabelModuleTYPE_COMPATIBLE {
            get {
                return ResourceManager.GetString("uiLabelModuleTYPE_COMPATIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No aircraft detected.
        /// </summary>
        internal static string uiLabelNoAircraftDetected_ {
            get {
                return ResourceManager.GetString("uiLabelNoAircraftDetected.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is now running in the background..
        /// </summary>
        internal static string uiMessageApplicationIsRunningInBackgroundMode {
            get {
                return ResourceManager.GetString("uiMessageApplicationIsRunningInBackgroundMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config file passed as parameter does not exist..
        /// </summary>
        internal static string uiMessageCmdParamConfigFileDoesNotExist {
            get {
                return ResourceManager.GetString("uiMessageCmdParamConfigFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This config line is not saved yet.
        ///Set the description text and use the edit button then..
        /// </summary>
        internal static string uiMessageConfigLineNotSavedYet {
            get {
                return ResourceManager.GetString("uiMessageConfigLineNotSavedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file not found. Please check path to config file..
        /// </summary>
        internal static string uiMessageConfigNotFound {
            get {
                return ResourceManager.GetString("uiMessageConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on loading presets. Presets are not available for selection..
        /// </summary>
        internal static string uiMessageConfigWizard_ErrorLoadingPresets {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ErrorLoadingPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets file not found in current directory..
        /// </summary>
        internal static string uiMessageConfigWizard_PresetsNotFound {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_PresetsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the address of the desired Led Display Module. It must be numeric, e.g. 1.
        /// </summary>
        internal static string uiMessageConfigWizard_ProvideLedDisplayAddress {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ProvideLedDisplayAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a module by choosing a valid serial from the list..
        /// </summary>
        internal static string uiMessageConfigWizard_SelectArcaze {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectArcaze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value for comparison..
        /// </summary>
        internal static string uiMessageConfigWizard_SelectComparison {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_SelectComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown precondition type from config.
        /// </summary>
        internal static string uiMessageConfigWizard_UnknownPreconditionType {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_UnknownPreconditionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please review the value and provide a valid hex format (0-F)..
        /// </summary>
        internal static string uiMessageConfigWizard_ValidHexFormat {
            get {
                return ResourceManager.GetString("uiMessageConfigWizard_ValidHexFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only numbers allowed. Please check your input..
        /// </summary>
        internal static string uiMessageConfigWizardInterpolationOnlyNumbersPlease {
            get {
                return ResourceManager.GetString("uiMessageConfigWizardInterpolationOnlyNumbersPlease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes in your configuration.
        ///Do you want to save them now?.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsaved {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check.
        /// </summary>
        internal static string uiMessageConfirmDiscardUnsavedTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmDiscardUnsavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to create a new config?
        ///All unsaved changes will get lost..
        /// </summary>
        internal static string uiMessageConfirmNewConfig {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm.
        /// </summary>
        internal static string uiMessageConfirmNewConfigTitle {
            get {
                return ResourceManager.GetString("uiMessageConfirmNewConfigTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the device has already been used, please review..
        /// </summary>
        internal static string uiMessageDeviceNameAlreadyUsed {
            get {
                return ResourceManager.GetString("uiMessageDeviceNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for the device is not valid or too long (max. {1} characters). Don&apos;t use the following characters:
        ///{0}.
        /// </summary>
        internal static string uiMessageDeviceNameContainsInvalidCharsOrTooLong {
            get {
                return ResourceManager.GetString("uiMessageDeviceNameContainsInvalidCharsOrTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred on parsing your value formula. Please review and correct any errors..
        /// </summary>
        internal static string uiMessageErrorOnParsingExpression {
            get {
                return ResourceManager.GetString("uiMessageErrorOnParsingExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your firmware settings!
        ///You have to provide the path to a valid Arduino IDE installation (min 1.0.5)..
        /// </summary>
        internal static string uiMessageFirmwareCheckPath {
            get {
                return ResourceManager.GetString("uiMessageFirmwareCheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) firmware reset completed ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetComplete {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error on resetting the board(s):
        ///
        ///{0}
        ///
        ///Check log for more details..
        /// </summary>
        internal static string uiMessageFirmwareResetError {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} on {1} (Module {2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetStatus {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board reset was successful!.
        /// </summary>
        internal static string uiMessageFirmwareResetSuccessful {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) firmware reset timed out ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareResetTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board reset.
        /// </summary>
        internal static string uiMessageFirmwareResetTitle {
            get {
                return ResourceManager.GetString("uiMessageFirmwareResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) firmware update completed ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateComplete {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating {0} on {1} (Module {2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateStatus {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) firmware update timed out ({2}/{3}).
        /// </summary>
        internal static string uiMessageFirmwareUpdateTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUpdateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some boards can&apos;t be auto-flashed because the board type is ambiguous:
        ///
        ///{0}
        ///
        ///Please manually flash the boards using &quot;upload firmware&quot; and select the correct board type from the menu..
        /// </summary>
        internal static string uiMessageFirmwareUploadAmbiguousBoards {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadAmbiguousBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error on uploading the firmware for the board(s):
        ///
        ///{0}
        ///
        ///Check log for more details..
        /// </summary>
        internal static string uiMessageFirmwareUploadError {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update was successful!.
        /// </summary>
        internal static string uiMessageFirmwareUploadSuccessful {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware upload experienced a timeout..
        /// </summary>
        internal static string uiMessageFirmwareUploadTimeout {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        internal static string uiMessageFirmwareUploadTitle {
            get {
                return ResourceManager.GetString("uiMessageFirmwareUploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flight Simulator has been closed. Execution of config has been stopped. Restart your flight simulator to restart config..
        /// </summary>
        internal static string uiMessageFsHasBeenStopped {
            get {
                return ResourceManager.GetString("uiMessageFsHasBeenStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiply value must contain a valid number..
        /// </summary>
        internal static string uiMessageFsuipcConfigPanelMultiplyWrongFormat {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConfigPanelMultiplyWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be empty. Use numbers or expressions like $+1, etc..
        /// </summary>
        internal static string uiMessageFsuipcConfigPanelNoValue {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConfigPanelNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to FSUIPC got lost.
        /// </summary>
        internal static string uiMessageFsuipcConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageFsuipcConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on downloading HubHop presets. Please check the Log for more information..
        /// </summary>
        internal static string uiMessageHubHopUpdateError {
            get {
                return ResourceManager.GetString("uiMessageHubHopUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HubHop presets download was successful..
        /// </summary>
        internal static string uiMessageHubHopUpdateSuccessful {
            get {
                return ResourceManager.GetString("uiMessageHubHopUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your Arduino IDE installation. The path cannot be used, avrdude has not been found..
        /// </summary>
        internal static string uiMessageInvalidArduinoIdePath {
            get {
                return ResourceManager.GetString("uiMessageInvalidArduinoIdePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Value! Only use hex-encoded numbers..
        /// </summary>
        internal static string uiMessageInvalidValueHexOnly {
            get {
                return ResourceManager.GetString("uiMessageInvalidValueHexOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot add another {1}. The maximum is {0} on a {2}..
        /// </summary>
        internal static string uiMessageMaxNumberOfDevicesReached {
            get {
                return ResourceManager.GetString("uiMessageMaxNumberOfDevicesReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFConnector still active.
        /// </summary>
        internal static string uiMessageMFConnectorInterfaceActive {
            get {
                return ResourceManager.GetString("uiMessageMFConnectorInterfaceActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following midiboard is currently in usage by another process:
        ///
        ///{0}
        ///
        ///That midiboard cannot be used until other application is terminated and MobiFlight is restarted..
        /// </summary>
        internal static string uiMessageMidiBoardInUsageByOtherProcess {
            get {
                return ResourceManager.GetString("uiMessageMidiBoardInUsageByOtherProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old config format (&lt; 6.0) found. The config file has to be converted to work correctly. Do you want to use a new filename?.
        /// </summary>
        internal static string uiMessageMigrateConfigFileV60YesNo {
            get {
                return ResourceManager.GetString("uiMessageMigrateConfigFileV60YesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The config file has to be converted to work correctly. Please save with new file extension..
        /// </summary>
        internal static string uiMessageMigrateConfigFileYesNo {
            get {
                return ResourceManager.GetString("uiMessageMigrateConfigFileYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show detected modules.
        /// </summary>
        internal static string uiMessageModuleFound {
            get {
                return ResourceManager.GetString("uiMessageModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The board &quot;{0}&quot; ({1}) disconnected..
        /// </summary>
        internal static string uiMessageModuleRemoved {
            get {
                return ResourceManager.GetString("uiMessageModuleRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that your arcaze modules are not configured. This is a new feature to better support &quot;Extension Modules&quot;.
        ///
        ///You should configure them now..
        /// </summary>
        internal static string uiMessageModulesNotConfiguredYet {
            get {
                return ResourceManager.GetString("uiMessageModulesNotConfiguredYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight Update available!.
        /// </summary>
        internal static string uiMessageNewUpdateAvailable {
            get {
                return ResourceManager.GetString("uiMessageNewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEAH! - New Version {0} is available! Please update now..
        /// </summary>
        internal static string uiMessageNewUpdateAvailablePleaseUpdate {
            get {
                return ResourceManager.GetString("uiMessageNewUpdateAvailablePleaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active FSUIPC connection..
        /// </summary>
        internal static string uiMessageNoFSUIPCConnection {
            get {
                return ResourceManager.GetString("uiMessageNoFSUIPCConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No modules found.
        /// </summary>
        internal static string uiMessageNoModuleFound {
            get {
                return ResourceManager.GetString("uiMessageNoModuleFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already can reference all available configs. Adding more doesn&apos;t make sense..
        /// </summary>
        internal static string uiMessageNoMoreConfigReferenceAvailable {
            get {
                return ResourceManager.GetString("uiMessageNoMoreConfigReferenceAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no missing joysticks found..
        /// </summary>
        internal static string uiMessageNoNotConnectedJoysticksInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNoNotConnectedJoysticksInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no missing midiboards found..
        /// </summary>
        internal static string uiMessageNoNotConnectedMidiBoardsInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNoNotConnectedMidiBoardsInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no orphaned serials in the current config..
        /// </summary>
        internal static string uiMessageNoOrphanedSerialsFound {
            get {
                return ResourceManager.GetString("uiMessageNoOrphanedSerialsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active SimConnect Connection.
        /// </summary>
        internal static string uiMessageNoSimConnectConnection {
            get {
                return ResourceManager.GetString("uiMessageNoSimConnectConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following joysticks are currently not connected but referenced in the config:
        ///
        ///{0}
        ///
        ///Respective configs won&apos;t work until joysticks are connected and you have restarted MobiFlight..
        /// </summary>
        internal static string uiMessageNotConnectedJoysticksInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNotConnectedJoysticksInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following midiboards are currently not connected but referenced in the config:
        ///
        ///{0}
        ///
        ///Respective configs won&apos;t work until midiboards are connected and you have restarted MobiFlight..
        /// </summary>
        internal static string uiMessageNotConnectedMidiBoardsInConfigFound {
            get {
                return ResourceManager.GetString("uiMessageNotConnectedMidiBoardsInConfigFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough pins.
        /// </summary>
        internal static string uiMessageNotEnoughPinsHint {
            get {
                return ResourceManager.GetString("uiMessageNotEnoughPinsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free pins to add this device.
        /// </summary>
        internal static string uiMessageNotEnoughPinsMessage {
            get {
                return ResourceManager.GetString("uiMessageNotEnoughPinsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not implemented yet..
        /// </summary>
        internal static string uiMessageNotImplementedYet {
            get {
                return ResourceManager.GetString("uiMessageNotImplementedYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running the latest version {0}. No update necessary..
        /// </summary>
        internal static string uiMessageNoUpdateNecessary {
            get {
                return ResourceManager.GetString("uiMessageNoUpdateNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active X-Plane connection.
        /// </summary>
        internal static string uiMessageNoXplaneConnection {
            get {
                return ResourceManager.GetString("uiMessageNoXplaneConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a number and greater than 0..
        /// </summary>
        internal static string uiMessagePanelsStepperInputRevolutionsMustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("uiMessagePanelsStepperInputRevolutionsMustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not be empty..
        /// </summary>
        internal static string uiMessagePanelsStepperInputRevolutionsMustNonEmpty {
            get {
                return ResourceManager.GetString("uiMessagePanelsStepperInputRevolutionsMustNonEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precondition is not satisfied.
        /// </summary>
        internal static string uiMessagePreconditionNotSatisfied {
            get {
                return ResourceManager.GetString("uiMessagePreconditionNotSatisfied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Config could not be loaded. Please check for syntax errors..
        /// </summary>
        internal static string uiMessageProblemLoadingConfig {
            get {
                return ResourceManager.GetString("uiMessageProblemLoadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to uninstall the MobiFlight firmware? All your data will be removed from the board..
        /// </summary>
        internal static string uiMessageResetConfirm {
            get {
                return ResourceManager.GetString("uiMessageResetConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Board.
        /// </summary>
        internal static string uiMessageResetHint {
            get {
                return ResourceManager.GetString("uiMessageResetHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will require a restart of MobiFlight to become effective..
        /// </summary>
        internal static string uiMessageRestartRequired {
            get {
                return ResourceManager.GetString("uiMessageRestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected module does not contain any input devices. Do you want to add such devices?.
        /// </summary>
        internal static string uiMessageSelectedModuleDoesNotContainAnyInputDevices {
            get {
                return ResourceManager.GetString("uiMessageSelectedModuleDoesNotContainAnyInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected module does not contain any output devices. Do you want to add such devices?.
        /// </summary>
        internal static string uiMessageSelectedModuleDoesNotContainAnyOutputDevices {
            get {
                return ResourceManager.GetString("uiMessageSelectedModuleDoesNotContainAnyOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current firmware does not support this function. Please update to the latest firmware now!.
        /// </summary>
        internal static string uiMessageSettingsDialogFirmwareVersionTooLowException {
            get {
                return ResourceManager.GetString("uiMessageSettingsDialogFirmwareVersionTooLowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old firmware, update now!.
        /// </summary>
        internal static string uiMessageSettingsDlgOldFirmware {
            get {
                return ResourceManager.GetString("uiMessageSettingsDlgOldFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to SimConnect got lost..
        /// </summary>
        internal static string uiMessageSimConnectConnectionLost {
            get {
                return ResourceManager.GetString("uiMessageSimConnectConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} matches found..
        /// </summary>
        internal static string uiMessagesSimConnectPanelMatchesFound {
            get {
                return ResourceManager.GetString("uiMessagesSimConnectPanelMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - show all -.
        /// </summary>
        internal static string uiMessagesSimConnectPanelShowAll {
            get {
                return ResourceManager.GetString("uiMessagesSimConnectPanelShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during Test-Mode: Module not connected..
        /// </summary>
        internal static string uiMessageTestModeModuleNotConnected {
            get {
                return ResourceManager.GetString("uiMessageTestModeModuleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform Error. .
        /// </summary>
        internal static string uiMessageTransformError {
            get {
                return ResourceManager.GetString("uiMessageTransformError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to disable the automatic upload to new modules?
        ///You can always enable it later again in the settings menu..
        /// </summary>
        internal static string uiMessageUpdateArduinoFwAutoDisableYesNo {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoFwAutoDisableYesNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules found that are compatible with MobiFlight. To be able to use them they require the latest MobiFlight Firmware.
        ///
        ///Upload the MobiFlight Firmware now!.
        /// </summary>
        internal static string uiMessageUpdateArduinoOkCancel {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoOkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compatible boards found!.
        /// </summary>
        internal static string uiMessageUpdateArduinoTitle {
            get {
                return ResourceManager.GetString("uiMessageUpdateArduinoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Mobiflight Boards have an old firmware - update them now?.
        /// </summary>
        internal static string uiMessageUpdateOldFirmwareOkCancel {
            get {
                return ResourceManager.GetString("uiMessageUpdateOldFirmwareOkCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Firmware Available!.
        /// </summary>
        internal static string uiMessageUpdateOldFirmwareTitle {
            get {
                return ResourceManager.GetString("uiMessageUpdateOldFirmwareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice! You updated successfully from {1} to {2}..
        /// </summary>
        internal static string uiMessageUpdateSuccessful {
            get {
                return ResourceManager.GetString("uiMessageUpdateSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to update your module with the current configuration?.
        /// </summary>
        internal static string uiMessageUploadConfigurationConfirm {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload finished..
        /// </summary>
        internal static string uiMessageUploadConfigurationFinished {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload finished with error..
        /// </summary>
        internal static string uiMessageUploadConfigurationFinishedWithError {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationFinishedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload configuration.
        /// </summary>
        internal static string uiMessageUploadConfigurationHint {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your config is too long, make some labels shorter.
        /// </summary>
        internal static string uiMessageUploadConfigurationTooLong {
            get {
                return ResourceManager.GetString("uiMessageUploadConfigurationTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be a valid number..
        /// </summary>
        internal static string uiMessageValidationMustBeNumber {
            get {
                return ResourceManager.GetString("uiMessageValidationMustBeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be a number between {0} and {1}..
        /// </summary>
        internal static string uiMessageValidNumberInRange {
            get {
                return ResourceManager.GetString("uiMessageValidNumberInRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest WASM Events could not be installed. Please check Log for more information..
        /// </summary>
        internal static string uiMessageWasmEventsInstallationError {
            get {
                return ResourceManager.GetString("uiMessageWasmEventsInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest WASM Events installed successfully..
        /// </summary>
        internal static string uiMessageWasmEventsInstallationSuccessful {
            get {
                return ResourceManager.GetString("uiMessageWasmEventsInstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module is already installed and up-to-date..
        /// </summary>
        internal static string uiMessageWasmUpdateAlreadyInstalled {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateAlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSFS2020 Community Folder was not found. Can&apos;t install WASM Module automatically. Please copy the folder manually..
        /// </summary>
        internal static string uiMessageWasmUpdateCommunityFolderNotFound {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateCommunityFolderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module was not installed successfully. Please check the Log for more information..
        /// </summary>
        internal static string uiMessageWasmUpdateInstallationError {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateInstallationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module installed successfully..
        /// </summary>
        internal static string uiMessageWasmUpdateInstallationSuccessful {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdateInstallationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiFlight WASM Module Installation.
        /// </summary>
        internal static string uiMessageWasmUpdater {
            get {
                return ResourceManager.GetString("uiMessageWasmUpdater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires I2C pins however {1} doesn&apos;t have any defined..
        /// </summary>
        internal static string uiNoI2CPinsDefined {
            get {
                return ResourceManager.GetString("uiNoI2CPinsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No I2C pins defined.
        /// </summary>
        internal static string uiNoI2CPinsDefinedHint {
            get {
                return ResourceManager.GetString("uiNoI2CPinsDefinedHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Param.
        /// </summary>
        internal static string uiPmdgEventIdInputPanelCustomParam {
            get {
                return ResourceManager.GetString("uiPmdgEventIdInputPanelCustomParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will require a restart of MobiFlight to become effective..
        /// </summary>
        internal static string uiSettingsMobiFlightChangeRequiresRestart {
            get {
                return ResourceManager.GetString("uiSettingsMobiFlightChangeRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mobiflight.com/en/tutorials/community-guides/expression-syntax-guide.html.
        /// </summary>
        internal static string WebsiteHelpNcalc {
            get {
                return ResourceManager.GetString("WebsiteHelpNcalc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.mobiflight.com/en/documentation/software.html.
        /// </summary>
        internal static string WebsiteUrlHelp {
            get {
                return ResourceManager.GetString("WebsiteUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPUIPC Status.
        /// </summary>
        internal static string xpuipcStatus {
            get {
                return ResourceManager.GetString("xpuipcStatus", resourceCulture);
            }
        }
    }
}
