name: Build

on:
  workflow_call:
    inputs:
      solution_file:
        description: The solution to build/restore
        required: false
        type: string

      project_file:
        description: The project to build
        required: true
        type: string

      test_projects:
        description: The test projects
        required: false
        type: string

      build_configuration:
        description: The build configuration
        required: false
        type: string
        default: Release

      publish_path:
        description: The path to publish the solution/project under 
        required: false
        type: string

      publish_version:
        description: The version for publishing 
        required: false
        type: string

jobs:
  build:
    runs-on: windows-latest

    env:
      RESTORE_PATH: ${{ inputs.solution_file != '' && inputs.solution_file || inputs.project_files }}

    steps:
      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build -c ${{ inputs.build_configuration }} ${{ env.RESTORE_PATH }} --no-restore

      - name: dotnet test
        if: ${{ inputs.test_projects != '' }}
        run: dotnet test -c ${{ inputs.build_configuration }} ${{ env.RESTORE_PATH }} --no-build

      - name: publish
        if: ${{ inputs.publish_path != '' }}
        run: dotnet publish -c ${{ inputs.build_configuration }} -p:Version="${{ inputs.publish_version }}" ${{ inputs.project_files }} -o ${{ inputs.publish_path }}
