name: CI Pipeline

on:
  workflow_dispatch:
  pull_request:
    branches: [main, hotfix/*]

env:
  SOLUTION_FILE_PATH: MobiFlightConnector.sln
  BUILD_CONFIGURATION: Release
  BUILD_PLATFORM: x86
  VERSION: "0.0.${{ github.event.number }}.${{ github.run_number }}"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v7

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.x'
          architecture: '${{ env.BUILD_PLATFORM }}'

      - name: Build frontend
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: cd src/MobiFlightConnector/frontend; npm install; npm run build

      - name: Create artifacts
        run: |
          mkdir dist

      - name: dotnet restore
        run: dotnet restore

      - name: dotnet build
        run: dotnet build -c ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} --no-restore

      # - name: dotnet test
      #   run: dotnet test -c ${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} --no-build

      - name: publish MobiFlightConnector
        run: dotnet publish -c ${{env.BUILD_CONFIGURATION}} -p:Version="${{ env.VERSION }}" src/MobiFlightConnector/MobiFlightConnector.csproj -o dist/MobiFlightConnector-${{ env.VERSION }} --no-build

      - name: publish MobiFlightInstaller
        run: dotnet publish -c ${{env.BUILD_CONFIGURATION}} -p:Version="${{ env.VERSION }}" src/MobiFlight-Installer/MobiFlightInstaller.csproj -o dist/MobiFlightInstaller-${{ env.VERSION }} --no-build

      - name: copy installer to dist
        run: |
          copy dist/MobiFlightInstaller-${{ env.VERSION }}/MobiFlight-Installer.exe dist/MobiFlightConnector-${{ env.VERSION }}/

          cd dist/MobiFlightConnector-${{ env.VERSION }}

          & "${{ github.workspace }}\Build\utils\7z\7z.exe" a ../MobiFlightConnector-${{ env.VERSION }}.zip * -r

      - name: store latest setup file
        uses: actions/upload-artifact@v7
        with:
          name: MobiFlightConnector
          path: |
            dist/MobiFlightConnector-${{ env.VERSION }}.zip
