name: Add PR Artifact Links As Comment
on:
  workflow_run:
    workflows: [CI Pipeline, Playwright Tests]
    types: [completed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

jobs:
  call-artifact-links:
    name: Add artifact links to pull request
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Determine PR number
        id: pr-number
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "PR_NUMBER=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            PR_NUM="${{ github.event.workflow_run.pull_requests[0].number || 0 }}"
            echo "PR_NUMBER=$PR_NUM" >> $GITHUB_ENV
          fi
          
      - name: Call artifact links workflow
        uses: ./.github/workflows/add-artifact-links.yml
        with:
          pr_number: ${{ fromJSON(env.PR_NUMBER) }}
        secrets:
          token: ${{ secrets.GITHUB_TOKEN }}
