name: Add PR Artifact Links As Comment
on:
  workflow_run:
    workflows: [CI Pipeline, Playwright Tests]
    types: [completed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

jobs:
  call-artifact-links:
    name: Add artifact links to pull request
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/add-artifact-links.yml
    with:
      pr_number: ${{
        (github.event_name == 'workflow_dispatch' && fromJSON(github.event.inputs.pr_number))
        || default(github.event.workflow_run.pull_requests[0].number, 0)
      }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
