name: Add artifact links to pull request
on:
  workflow_run:
    workflows: [RunTests]
    types: [completed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

jobs:
  prepare-inputs:
    name: Prepare inputs for artifact links
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    outputs:
      pr_number: ${{ steps.set-inputs.outputs.pr_number }}
      workflow_run_id: ${{ steps.set-inputs.outputs.workflow_run_id }}
    steps:
      - name: Set inputs
        id: set-inputs
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_PR_NUMBER: ${{ github.event.inputs.pr_number }}
          WR_PR_NUMBER: ${{ github.event.workflow_run.pull_requests[0].number || '' }}
          WR_ID: ${{ github.event.workflow_run.id || '' }}
        run: |
          if [ "$EVENT_NAME" = "workflow_dispatch" ]; then
            echo "pr_number=$INPUT_PR_NUMBER" >> $GITHUB_OUTPUT
            echo "workflow_run_id=null" >> $GITHUB_OUTPUT
          else
            echo "pr_number=$WR_PR_NUMBER" >> $GITHUB_OUTPUT
            echo "workflow_run_id=$WR_ID" >> $GITHUB_OUTPUT
          fi

  call-artifact-links:
    name: Add artifact links to pull request
    needs: prepare-inputs
    uses: ./.github/workflows/add-artifact-links.yml
    with:
      pr_number: ${{ fromJSON(needs.prepare-inputs.outputs.pr_number) }}
      workflow_run_id: ${{ needs.prepare-inputs.outputs.workflow_run_id != 'null' && fromJSON(needs.prepare-inputs.outputs.workflow_run_id) || null }}
      comment_title: 'Build for this pull request'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
