name: Add artifact links to pull request
on:
  workflow_run:
    workflows: [RunTests]
    types: [completed]
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull request number'
        required: true
        type: number

jobs:
  call-artifact-links:
    name: Add artifact links to pull request
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    uses: ./.github/workflows/add-artifact-links.yml
    with:
      pr_number: ${{ github.event.inputs.pr_number || (github.event.workflow_run.pull_requests[0].number || null) }}
      workflow_run_id: ${{ github.event.workflow_run.id || null }}
      comment_title: 'Build for this pull request'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
