name: Check translations
on:
  pull_request:
    branches: [main, hotfix/*]
    paths:
      # Trigger only when files in the public/locales folder change
      - "src/MobiFlightConnector/frontend/public/locales/**"

  workflow_dispatch:

jobs:
  check-translations:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/MobiFlightConnector/frontend
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci

      - name: Check Translations
        run: node src/scripts/check-translations.js

      - name: Generate Translation Statistics as Markdown
        run: echo "$(node src/scripts/check-translations.js)" > translation-stats.md

      - name: Post Translation Statistics
        uses: marocchino/sticky-pull-request-comment@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path: src/MobiFlightConnector/frontend/translation-stats.md
